version: '3'
services:
  db:
    image: postgres:14.4
    restart: always
    container_name: db
    expose:
      - "5432"
    volumes:
      - ./docker/postgres-multiple-databases.sh:/docker-entrypoint-initdb.d/postgres-multiple-databases.sh
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_MULTIPLE_DATABASES: db_blog,db_blog_test
    ports:
      - "5432:5432"

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    restart: always
    working_dir: /var/www/html
    expose:
      - "9000"
    volumes:
      - .:/var/www/html
    links:
      - db:db

  web:
    image: nginx:latest
    container_name: web
    restart: always
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php:php
